USE Chinook;
SHOW TABLES;
DESCRIBE CUSTOMER;
DESCRIBE INVOICE;
DESCRIBE TRACK;
SELECT * FROM customer where Country='Brazil';
SELECT * FROM track WHERE UnitPrice>1.00;
SELECT * FROM customer WHERE email LIKE'%gmail%'; 
SELECT * FROM track ORDER BY Unitprice DESC LIMIT 10;
SELECT *FROM invoice ORDER BY InvoiceDate DESC LIMIT 5;
SELECT DISTINCT country from customer;
SELECT DISTINCT genreid FROM track;
SELECT * FROM customer WHERE company like 'A%';
SELECT * FROM invoice WHERE total BETWEEN 5 and 15;
SELECT *FROM customer WHERE country IN('USA','canada','mexico');
SELECT CONCAT(firstname,' ',lastname) AS Full_Name FROM customer;
SELECT name,UnitPrice ,UnitPrice + (UnitPrice*10/100) AS price_with_tax From track; 